# Generated by Django 5.0.2 on 2025-12-03 21:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Empresa')),
                ('subdomain', models.CharField(max_length=100, unique=True, verbose_name='Subdomínio')),
                ('domain', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Domínio Personalizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('primary_color', models.CharField(default='#007bff', max_length=7, verbose_name='Cor Primária')),
                ('logo_url', models.URLField(blank=True, null=True, verbose_name='URL do Logo')),
            ],
            options={
                'verbose_name': 'Inquilino (Tenant)',
                'verbose_name_plural': 'Inquilinos (Tenants)',
            },
        ),
    ]
