# Generated by Django 5.0.2 on 2025-12-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='weight_harsh_acceleration',
            field=models.IntegerField(default=5, verbose_name='Peso: Aceleração Brusca'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='weight_harsh_braking',
            field=models.IntegerField(default=5, verbose_name='Peso: Freada Brusca'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='weight_harsh_cornering',
            field=models.IntegerField(default=5, verbose_name='Peso: Curva Brusca'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='weight_overspeed',
            field=models.IntegerField(default=10, verbose_name='Peso: Excesso de Velocidade'),
        ),
    ]
