# Generated by Django 5.0.2 on 2025-12-04 16:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('traccar_device_id', models.IntegerField(unique=True, verbose_name='ID no Traccar')),
                ('name', models.CharField(max_length=100, verbose_name='Nome/Placa')),
                ('plate', models.CharField(blank=True, max_length=20, null=True, verbose_name='Placa')),
                ('model', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo')),
                ('last_position_lat', models.FloatField(blank=True, null=True)),
                ('last_position_lng', models.FloatField(blank=True, null=True)),
                ('last_speed', models.FloatField(default=0, verbose_name='Velocidade (km/h)')),
                ('last_update', models.DateTimeField(blank=True, null=True, verbose_name='Última Comunicação')),
                ('ignition', models.BooleanField(default=False, verbose_name='Ignição')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='tenants.tenant', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['name'],
            },
        ),
    ]
