# Generated by Django 5.0.2 on 2025-12-04 16:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
        ('tenants', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='current_km',
            field=models.FloatField(default=0, verbose_name='Km Atual'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(default='diesel', max_length=20, verbose_name='Combustível'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano'),
        ),
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Plano')),
                ('interval_km', models.IntegerField(verbose_name='Intervalo (Km)')),
                ('interval_days', models.IntegerField(blank=True, null=True, verbose_name='Intervalo (Dias)')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='Número de Série/DOT')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('position', models.CharField(choices=[('FL', 'Frente Esquerda'), ('FR', 'Frente Direita'), ('RL', 'Traseira Esquerda'), ('RR', 'Traseira Direita'), ('SPARE', 'Estepe'), ('STOCK', 'Estoque')], default='STOCK', max_length=10, verbose_name='Posição')),
                ('initial_tread_depth', models.FloatField(default=8.0, verbose_name='Sulco Inicial (mm)')),
                ('current_tread_depth', models.FloatField(default=8.0, verbose_name='Sulco Atual (mm)')),
                ('accumulated_km', models.FloatField(default=0, verbose_name='Km Acumulado')),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tires', to='fleet.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('description', models.TextField(verbose_name='Descrição do Serviço')),
                ('km_at_service', models.FloatField(verbose_name='Km no Serviço')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Custo Total')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('IN_PROGRESS', 'Em Andamento'), ('COMPLETED', 'Concluída'), ('CANCELED', 'Cancelada')], default='PENDING', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.maintenanceplan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='fleet.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
