# Generated by Django 5.0.2 on 2025-12-04 16:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_vehicle_current_km_vehicle_fuel_type_vehicle_year_and_more'),
        ('tenants', '0003_tenant_weight_harsh_acceleration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('date', models.DateField(verbose_name='Data Referência')),
                ('score', models.IntegerField(default=100, verbose_name='Pontuação')),
                ('overspeed_count', models.IntegerField(default=0)),
                ('harsh_acceleration_count', models.IntegerField(default=0)),
                ('harsh_braking_count', models.IntegerField(default=0)),
                ('harsh_cornering_count', models.IntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'Score Diário',
                'ordering': ['-date', '-score'],
                'unique_together': {('vehicle', 'date')},
            },
        ),
    ]
