# Generated by Django 5.0.2 on 2025-12-04 16:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_driverscore'),
        ('tenants', '0003_tenant_weight_harsh_acceleration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('start_time', models.DateTimeField(verbose_name='Início da Jornada')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Fim da Jornada')),
                ('status', models.CharField(choices=[('OPEN', 'Em Aberto'), ('CLOSED', 'Fechada')], default='OPEN', max_length=10)),
                ('total_driving_seconds', models.IntegerField(default=0)),
                ('total_meal_seconds', models.IntegerField(default=0)),
                ('total_rest_seconds', models.IntegerField(default=0)),
                ('total_wait_seconds', models.IntegerField(default=0)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='tenants.userprofile', verbose_name='Motorista')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.vehicle', verbose_name='Veículo Utilizado')),
            ],
            options={
                'verbose_name': 'Jornada de Trabalho',
                'verbose_name_plural': 'Jornadas',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ShiftEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('event_type', models.CharField(choices=[('START_SHIFT', 'Início de Jornada'), ('START_MEAL', 'Início Refeição'), ('END_MEAL', 'Fim Refeição'), ('START_REST', 'Início Descanso'), ('END_REST', 'Fim Descanso'), ('START_WAIT', 'Início Espera'), ('END_WAIT', 'Fim Espera'), ('END_SHIFT', 'Fim de Jornada')], max_length=20, verbose_name='Tipo de Evento')),
                ('timestamp', models.DateTimeField(verbose_name='Horário')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='fleet.workshift')),
            ],
            options={
                'verbose_name': 'Evento de Jornada',
                'ordering': ['timestamp'],
            },
        ),
    ]
