# Generated by Django 5.0.2 on 2025-12-04 16:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_workshift_shiftevent'),
        ('tenants', '0003_tenant_weight_harsh_acceleration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Rota')),
                ('date', models.DateField(verbose_name='Data da Entrega')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('OPTIMIZED', 'Otimizada'), ('IN_PROGRESS', 'Em Andamento'), ('COMPLETED', 'Concluída'), ('CANCELED', 'Cancelada')], default='DRAFT', max_length=20)),
                ('total_km_predicted', models.FloatField(default=0, verbose_name='Km Previsto')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.userprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'Rota de Entrega',
                'verbose_name_plural': 'Rotas de Entrega',
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('sequence', models.IntegerField(default=0, verbose_name='Ordem de Parada')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('VISITED', 'Visitado/Entregue'), ('FAILED', 'Falhou/Não Entregue')], default='PENDING', max_length=20)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('completion_time', models.DateTimeField(blank=True, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='fleet.deliveryroute')),
            ],
            options={
                'verbose_name': 'Parada',
                'ordering': ['sequence'],
            },
        ),
    ]
