# Generated by Django 5.0.2 on 2025-12-04 17:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_deliveryroute_routestop'),
        ('tenants', '0003_tenant_weight_harsh_acceleration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Cliente')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Mensal')),
                ('due_day', models.IntegerField(default=10, verbose_name='Dia de Vencimento')),
                ('start_date', models.DateField(verbose_name='Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fim')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('SUSPENDED', 'Suspenso'), ('CANCELED', 'Cancelado')], default='ACTIVE', max_length=20)),
                ('asaas_customer_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Asaas')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'Contrato',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('category', models.CharField(choices=[('IPVA', 'IPVA/Licenciamento'), ('INSURANCE', 'Seguro'), ('FUEL', 'Combustível'), ('MAINTENANCE', 'Manutenção'), ('OTHER', 'Outros')], max_length=20)),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('due_date', models.DateField(verbose_name='Vencimento')),
                ('paid_at', models.DateField(blank=True, null=True, verbose_name='Data Pagamento')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Pago')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'Despesa',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('infraction_date', models.DateField(verbose_name='Data da Infração')),
                ('description', models.CharField(max_length=200, verbose_name='Infração')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('points', models.IntegerField(default=0, verbose_name='Pontos na CNH')),
                ('due_date', models.DateField(verbose_name='Vencimento')),
                ('is_paid', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.userprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'Multa',
            },
        ),
    ]
